snack = ["Coke","CHips",50]
print(snack)
snack.append("Diet COke")
print(f"after adding snack{snack}")
snack.remove(50)
print(f"after removing 50{snack}")
snack.sort()
print(f"Afer sort it in albhatecial order{snack}")
snack.append("Cha")
print(snack)
snack.sort()
print(snack)
print(len(snack))
snack[3]="Pepsi"
print(f"after changing{snack}")
snack.insert(3,"Sausage")
print(snack)
del snack[0]
print(f"after delating Chips{snack}")
last_snack= snack.pop()
print(last_snack)
print(snack)
